# Site settings
title: René Ghosh Homepage
email: rene.ghosh@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  René Ghosh, writer and musician. Books, music, and links to articles.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://satelliteray.github.io" 
twitter_username: reghosh
github_username:  satelliteray
facebook: https://www.facebook.com/rene.ghosh
twitter: https://twitter.com/reghosh
soundcloud: https://soundcloud.com/satelliteray/
email: rene.ghosh@gmail.com
keywords: novel, fiction, music, magical punk, René Ghosh, open mic, music, Satellite Ray
# Build settings
markdown: kramdown
defaults:
  - scope:
      path:            "wip/**/*.*"
    values:
      sitemap:         false
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
collections:
  books:
    output: false
  music:
    output: false
  published:
    output: false
  extracts:
    output: true
  articles:
    output: true
  running:
    output: true
