# website content

books:
  - puppetdancers:
    title: Puppet Dancers
    image: images/puppetdancers-medium.jpeg
    release: 2014
    type: novel
    description: >
      *Puppet Dancers* is my first novel. It is available in both print and electronic form. If you don't feel like paying for it, just email me and I'll send it to you for free.  The novel is about a dance style. Known to Baguetelians as the robotic swerve and to Margolians as the puppet dance, its history is veiled in legend, but strange events uncovered by data analysts will reveal its true function, beyond Baguetelians' ironic imitation of laboratory robots or Margolians' nostalgia of lost empires.
